
import { Product, Category } from "./types";

export const categories: Category[] = [
  { id: "c1", name: "Electronics", slug: "electronics" },
  { id: "c2", name: "Clothing", slug: "clothing" },
  { id: "c3", name: "Home & Kitchen", slug: "home-kitchen" },
  { id: "c4", name: "Books", slug: "books" },
];

export const products: Product[] = [
  {
    id: "p9",
    name: "Wireless Bluetooth Speaker",
    description: "Enjoy high-quality sound with this portable wireless Bluetooth speaker.",
    price: 89.99,
    category: "c1",
    tags: ["electronics", "audio", "wireless"],
    image: "https://images.unsplash.com/photo-1529359744902-86b2ab9edaea?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.5,
    reviewCount: 100,
    inStock: true,
  },
  {
    id: "p10",
    name: "4K Ultra HD Smart TV",
    description: "Experience stunning picture quality with our 4K Ultra HD Smart TV.",
    price: 799.99,
    category: "c1",
    tags: ["electronics", "tv", "4k"],
    image: "https://images.unsplash.com/photo-1567690187548-f07b1d7bf5a9?q=80&w=736&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.8,
    reviewCount: 50,
    inStock: true,
  },
  {
    id: "p11",
    name: "Gaming Laptop",
    description: "High-performance gaming laptop with the latest graphics card.",
    price: 1499.99,
    category: "c1",
    tags: ["electronics", "gaming", "laptop"],
    image: "https://images.unsplash.com/photo-1611078489935-0cb964de46d6?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.7,
    reviewCount: 30,
    inStock: true,
  },
  {
    id: "p12",
    name: "Smartphone with 5G",
    description: "Stay connected with the latest 5G smartphone.",
    price: 999.99,
    category: "c1",
    tags: ["electronics", "smartphone", "5g"],
    image: "https://images.unsplash.com/photo-1575695342320-d2d2d2f9b73f?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.6,
    reviewCount: 40,
    inStock: true,
  },
  {
    id: "p13",
    name: "Action Camera",
    description: "Capture your adventures with this compact action camera.",
    price: 299.99,
    category: "c1",
    tags: ["electronics", "camera", "action"],
    image: "https://images.unsplash.com/photo-1603720913661-76d1053714e2?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.5,
    reviewCount: 20,
    inStock: true,
  },
  {
    id: "p14",
    name: "Stylish Denim Jacket",
    description: "A classic denim jacket that never goes out of style.",
    price: 59.99,
    category: "c2",
    tags: ["clothing", "jacket", "denim"],
    image: "https://media.istockphoto.com/id/854479460/photo/with-good-basics-youll-have-endless-options.jpg?s=612x612&w=is&k=20&c=B1PGrdkL7vuDXmqnRu_jZKak5aaSDaIvlwaOYvaTR4g=",
    rating: 4.5,
    reviewCount: 100,
    inStock: true,
  },
  {
    id: "p15",
    name: "Comfortable Running Shoes",
    description: "Lightweight and breathable running shoes for all-day comfort.",
    price: 79.99,
    category: "c2",
    tags: ["clothing", "shoes", "running"],
    image: "https://images.unsplash.com/photo-1562183241-b937e95585b6?q=80&w=765&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.6,
    reviewCount: 80,
    inStock: true,
  },
  {
    id: "p16",
    name: "Casual T-Shirt",
    description: "Soft and comfortable t-shirt for everyday wear.",
    price: 19.99,
    category: "c2",
    tags: ["clothing", "t-shirt", "casual"],
    image: "https://images.unsplash.com/photo-1503341733017-1901578f9f1e?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.4,
    reviewCount: 60,
    inStock: true,
  },
  {
    id: "p17",
    name: "Formal Dress Shirt",
    description: "A stylish dress shirt perfect for formal occasions.",
    price: 39.99,
    category: "c2",
    tags: ["clothing", "shirt", "formal"],
    image: "https://plus.unsplash.com/premium_photo-1723925110801-110c00d392a3?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.5,
    reviewCount: 20,
    inStock: true,
  },
  {
    id: "p18",
    name: "Winter Coat",
    description: "Stay warm with this insulated winter coat.",
    price: 129.99,
    category: "c2",
    tags: ["clothing", "coat", "winter"],
    image: "https://images.unsplash.com/photo-1577553187323-6afd9777d160?q=80&w=2048&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.7,
    reviewCount: 30,
    inStock: true,
  },
  {
    id: "p19",
    name: "Stainless Steel Cookware Set",
    description: "Durable and stylish stainless steel cookware set for all your cooking needs.",
    price: 199.99,
    category: "c3",
    tags: ["home", "kitchen", "cookware"],
    image: "https://images.unsplash.com/photo-1556910633-5099dc3971e8?q=80&w=1925&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.8,
    reviewCount: 90,
    inStock: true,
  },
  {
    id: "p20",
    name: "Electric Kettle",
    description: "Quickly boil water with this efficient electric kettle.",
    price: 39.99,
    category: "c3",
    tags: ["home", "kitchen", "kettle"],
    image: "https://images.unsplash.com/photo-1571552879083-e93b6ea70d1d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.5,
    reviewCount: 70,
    inStock: true,
  },
  {
    id: "p21",
    name: "Blender",
    description: "Make smoothies and soups with this powerful blender.",
    price: 59.99,
    category: "c3",
    tags: ["home", "kitchen", "blender"],
    image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?q=80&w=2105&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.6,
    reviewCount: 50,
    inStock: true,
  },
  {
    id: "p22",
    name: "Air Fryer",
    description: "Cook your favorite meals with less oil using this air fryer.",
    price: 89.99,
    category: "c3",
    tags: ["home", "kitchen", "air fryer"],
    image: "https://plus.unsplash.com/premium_photo-1672192166376-80b36e85cdb3?q=80&w=1935&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.7,
    reviewCount: 40,
    inStock: true,
  },
  {
    id: "p23",
    name: "Vacuum Cleaner Robot",
    description: "Keep your home clean with this efficient vacuum cleaner.",
    price: 149.99,
    category: "c3",
    tags: ["home", "cleaning", "vacuum"],
    image: "https://images.unsplash.com/photo-1603618090561-412154b4bd1b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.8,
    reviewCount: 30,
    inStock: true,
  },
  {
    id: "p24",
    name: "The Great Gatsby",
    description: "A classic novel by F. Scott Fitzgerald.",
    price: 14.99,
    category: "c4",
    tags: ["books", "classic", "novel"],
    image: "https://images.unsplash.com/photo-1615419235091-59bf9cbd530b?q=80&w=1172&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.5,
    reviewCount: 100,
    inStock: true,
  },
  {
    id: "p25",
    name: "1984 by George Orwell",
    description: "A dystopian novel that explores the dangers of totalitarianism.",
    price: 12.99,
    category: "c4",
    tags: ["books", "dystopian", "novel"],
    image: "https://images.unsplash.com/photo-1642936795750-ca25f7eab721?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.6,
    reviewCount: 80,
    inStock: true,
  },
  {
    id: "p26",
    name: "To Kill a Mockingbird",
    description: "A novel about the serious issues of race and rape.",
    price: 15.99,
    category: "c4",
    tags: ["books", "classic", "novel"],
    image: "https://m.media-amazon.com/images/I/81gepf1eMqL._SL1500_.jpg",
    rating: 4.7,
    reviewCount: 60,
    inStock: true,
  },
  {
    id: "p27",
    name: "Pride and Prejudice",
    description: "A romantic novel that critiques the British landed gentry.",
    price: 10.99,
    category: "c4",
    tags: ["books", "classic", "novel"],
    image: "https://images.unsplash.com/photo-1573125716783-d05b57a86488?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.5,
    reviewCount: 40,
    inStock: true,
  },
  {
    id: "p28",
    name: "The Catcher in the Rye",
    description: "A novel about teenage angst and alienation.",
    price: 13.99,
    category: "c4",
    tags: ["books", "classic", "novel"],
    image: "https://m.media-amazon.com/images/I/91fQEUwFMyL.jpg",
    rating: 4.6,
    reviewCount: 30,
    inStock: true,
  },

  {
    id: "p1",
    name: "Premium Wireless Headphones",
    description: "Experience crystal-clear sound with our premium noise-cancelling wireless headphones. Perfect for music lovers and professionals alike.",
    price: 299.99,
    discountedPrice: 249.99,
    category: "c1",
    tags: ["electronics", "audio", "wireless"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    rating: 4.8,
    reviewCount: 245,
    inStock: true,
    featured: true,
  },
  {
    id: "p2",
    name: "Ultra-Slim Laptop",
    description: "Powerful performance meets sleek design. This ultra-slim laptop is perfect for work and play, with a stunning display and all-day battery life.",
    price: 1299.99,
    category: "c1",
    tags: ["electronics", "computer", "laptop"],
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    rating: 4.9,
    reviewCount: 189,
    inStock: true,
    featured: true,
  },
  {
    id: "p3",
    name: "Smart Fitness Watch",
    description: "Track your fitness goals with precision. This smart watch monitors heart rate, sleep patterns, and activity levels while keeping you connected.",
    price: 199.99,
    discountedPrice: 169.99,
    category: "c1",
    tags: ["electronics", "wearable", "fitness"],
    image: "https://images.unsplash.com/photo-1696688713460-de12ac76ebc6?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c21hcnQlMjBmaXRuZXNzJTIwd2F0Y2h8ZW58MHx8MHx8fDA%3D",
    rating: 4.6,
    reviewCount: 312,
    inStock: true,
  },
  {
    id: "p4",
    name: "Premium Merino Wool Sweater",
    description: "Luxuriously soft and warm merino wool sweater designed for comfort and style. Perfect for cool evenings and winter days.",
    price: 129.99,
    category: "c2",
    tags: ["clothing", "wool", "winter"],
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    rating: 4.7,
    reviewCount: 98,
    inStock: true,
  },
  {
    id: "p5",
    name: "Handcrafted Ceramic Dinnerware Set",
    description: "Elevate your dining experience with our artisan-made ceramic dinnerware. Each piece is uniquely crafted with attention to detail.",
    price: 189.99,
    category: "c3",
    tags: ["home", "kitchen", "dining"],
    image: "https://images.unsplash.com/photo-1610701596061-2ecf227e85b2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    rating: 4.8,
    reviewCount: 75,
    inStock: true,
    featured: true,
  },
  {
    id: "p6",
    name: "Bestselling Novel Collection",
    description: "Immerse yourself in captivating stories with this collection of five award-winning novels from acclaimed authors.",
    price: 79.99,
    category: "c4",
    tags: ["books", "reading", "collection"],
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    rating: 4.5,
    reviewCount: 201,
    inStock: true,
  },
  {
    id: "p7",
    name: "Professional Camera Kit",
    description: "Capture life's moments with exceptional clarity using our professional-grade camera kit, complete with premium lenses and accessories.",
    price: 1499.99,
    discountedPrice: 1299.99,
    category: "c1",
    tags: ["electronics", "camera", "photography"],
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    rating: 4.9,
    reviewCount: 87,
    inStock: true,
  },
  {
    id: "p8",
    name: "Modern Coffee Table",
    description: "Add sophistication to your living space with this modern coffee table featuring clean lines, sturdy construction, and elegant design.",
    price: 349.99,
    category: "c3",
    tags: ["home", "furniture", "living room"],
    image: "https://images.unsplash.com/photo-1567016376408-0226e4d0c1ea?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    rating: 4.6,
    reviewCount: 64,
    inStock: true,
  },
];

export const getFeaturedProducts = (): Product[] => {
  return products.filter(product => product.featured);
};

export const getProductsByCategory = (categoryId: string): Product[] => {
  return products.filter(product => product.category === categoryId);
};

export const getProductById = (id: string): Product | undefined => {
  return products.find(product => product.id === id);
};

export const getRelatedProducts = (productId: string, limit = 4): Product[] => {
  const currentProduct = getProductById(productId);
  if (!currentProduct) return [];
  
  return products
    .filter(product => 
      product.id !== productId && 
      (product.category === currentProduct.category || 
       product.tags.some(tag => currentProduct.tags.includes(tag)))
    )
    .slice(0, limit);
};
